version: '3.7'
services:

#app
  app:
    logging:
      driver: none
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/myandel/admin-panel:master
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      - SERVICE_NAME=app
      - SERVICE_TAGS=dev
    env_file:
      - app.env

    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_network

#nginx
  web_server:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app_network

#redis
  cache_server:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"
    networks:
      - app_network

#mariadb
  database_server:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Myandel@1
      MYSQL_USER: myandel
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: myandel
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
